# Generated by Django 3.2.3 on 2021-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=155)),
                ('lastname', models.CharField(max_length=155)),
                ('dob', models.DateField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
