# Generated by Django 3.2.3 on 2021-05-27 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='lastname',
            field=models.CharField(default='noname', max_length=155),
        ),
    ]
